---
- name: enable repos
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
  - haproxy
    
  tags: 
  - haproxy   

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  
  roles:
  - postgres

- name: deploy tomcat
  hosts: apps
  gather_facts: false
  become: true

  roles:
  - tomcat
  
  tags: 
  - tomcat 


- name: deploy apache
  gather_facts: false
  become: true
  hosts: apps
  
  roles:
  - httpd 

  tags: 
  - httpd 

- name: Set index.html on app 1
  hosts: apps
  gather_facts: true
  become: true
  vars:
    inventory_hostname: app1
  tasks:
  - name: copy static index.html to tomcat app1
    template:
      src: index.html.j2
      dest: /usr/share/tomcat/webapps/ansible/index.html
    when: ansible_hostname == "app1"
    tags: 
    - index     
    
    
- name: Set index.html on app 2
  hosts: app
  gather_facts: true
  become: true
  vars:
    inventory_hostname: app2

  tasks:
  - name: copy static index.html to app2
    template:
      src: index.html.j2
      dest: /usr/share/tomcat/webapps/ansible/index.html
    when: ansible_hostname == "app2"
    tags: 
    - index 

