---
- name: enable repos
  hosts: all
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644

- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  roles:
  - haproxy
    
  tags: 
  - haproxy   

- name: deploy postgres
  gather_facts: false
  become: true
  hosts: appdbs
  
  roles:
  - postgres

  tags: 
  - postgres   

- name: deploy tomcat
  hosts: apps
  gather_facts: true
  become: true

  roles:
  - tomcat
  
  tags: 
  - tomcat 



 
    
    


