  - name: install postgres
    yum:
      name: postgresql-server
      state: latest
  - name: enable postgres at boot
    service:
      name: postgresql
      enabled: yes

  - name: Check for postgress data     
    stat: path=/var/lib/pgsql/data
    register: pgdb

  - name: initilize postgres
    command: postgresql-setup initdb
    when: not pgdb.stat.exists
    
  - name: initilize postgres some more
    command: chkconfig postgresql on
    
  - name: start postgres service
    service:
      name: postgresql.service
      state: started